# Generated by Django 3.2.8 on 2021-10-09 20:42

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.CharField(default=backend.models.generate_unique_cid, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.CharField(default=backend.models.generate_unique_pid, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('cost_for_one', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('image', models.URLField(max_length=250)),
                ('size', models.CharField(default='NONE', max_length=250, null=True)),
                ('color', models.CharField(default='NONE', max_length=250, null=True)),
                ('stock_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
            ],
        ),
    ]
