# Generated by Django 3.2.8 on 2021-10-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='owner',
            field=models.CharField(max_length=250),
        ),
    ]
