# Generated by Django 3.2.8 on 2021-10-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
