# Generated by Django 3.2.8 on 2021-10-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_review_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='owner',
        ),
    ]
