# Generated by Django 3.2.8 on 2021-10-13 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0010_shoppingcartitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcartitem',
            unique_together={('user', 'product')},
        ),
    ]
